main: kernitus.plugin.OldCombatMechanics.OCMMain
name: OldCombatMechanics
version: ${project.version}
authors: [kernitus, Rayzr522]
description: Reverts to pre-1.9 combat mechanics
load: POSTWORLD
api-version: 1.13

